lexema               cat      tipo    addr nivel escopo extra
-------------------- -------- ------- ---- ----- ------ -----
subrotinas           prog     nenhum    -1     0      0     0
a                    var      int        0     0      0     0
b                    var      int        1     0      0     0
res                  var      int        2     0      0     0
maximo               fn       int       -1     0      0     2
x                    param    int        0     0      2     0
y                    param    int        1     0      2     0
absoluto             fn       int       -1     0      0     3
n                    param    int        0     0      3     0
imprime_duplo        proc     nenhum    -1     0      0     4
n                    param    int        0     0      4     0
main                 proc     nenhum    -1     0      0     0
